### PR TITLE
Refactor the module to better follow the best-practices

### PR DESCRIPTION
**Pull request by MattiasGees**
I stripped the init module to multiple files to make it clear what every part does.

### CODE REVIEW

**Comment by amoswood** [comment]
@MattiasGees , I have very little time available to work on this module nor really support it. I like the refactors, but they need to be manually tested at this point since there are no automated tests written for it. Also, our company is moving away from using Neo4j in the very near future.

All that being said and with your refactors that you did, I was wondering if you want to take over the ownership of this module? I would be happy to transfer the ownership to you or make you a contributor on my module. What do you think?

**Comment by amoswood** [comment]
@MattiasGees , so do you think that you would be interested in taking over support for this?

**Comment by mlambrichs** [comment]
Hi Amos, if Mattias is not responding, I'm willing to take over support for this one.

**Comment by amoswood** [comment]
@mlambrichs , It would be fine if you wanted to take it over. I have never handed off a puppet module project before. So, any guidance would be appreciated.

**Comment by mlambrichs** [comment]
@amoswood 
The steps to take are these:
- you have to release your module one more time with release number 99.99.99
- in that release, make a reference to the module https://forge.puppetlabs.com/mlambrichs/neo4j in your README.md.

This is an example: https://forge.puppetlabs.com/puppetlabs/mcollective

**Comment by mlambrichs** [comment]
@MattiasGees Merged your branch into https://github.com/mlambrichs/puppet-neo4j/tree/skyscrapers-neo4j_refactor. Checking that, and will merge into master asap.

**Comment by amoswood** [comment]
@mlambrichs , I released version 99.99.99 to the forge this morning. Thank you again for taking over this module and continuing with it. I am sure that a lot of people are grateful.

**Pull request closed without merging**
