### PR TITLE
Added ha_initial_hosts functionality

### PR DESCRIPTION
**Pull request by lynxman**
I tried to use the module to create a neo4j HA cluster, which didn't match what the documentation said.

Looking at the module I saw the initial_hosts class but decided to ask the full string straight on the main class as I was feeding it from hiera.

Hope it is useful even if it is as a temporary solution!

### CODE REVIEW

**Comment by pbarber** [comment]
@amoswood I'm interested in getting this functionality from a puppet forge release - it looks like it wasn't added to the recent 1.1.0 release, is there a reason? Thanks for maintaining this module.

**Comment by amoswood** [comment]
@pbarber , I didn't include this code due to time constraints and your breaking changes. 

Also, the initial host idea is currently supported by using the type "neo4j::initial_host" and exporting those like:

    @@::neo4j::initial_host { "neo4j-${ha_cluster_name}-${::ipaddress}-5001" :
      ip              => $::ipaddress,
      ha_cluster_name => $ha_cluster_name,
    }

and then collecting them

     ::Neo4j::Initial_host <<| ha_cluster_name == $ha_cluster_name |>>

This is how that I use the module in our profile module. However, I see the benefit of using it like you have it too. The only thing that you put in your code which would break is the "fail" statement should it not be entered. If you want to modify your code and do another pull request, I would be happy to review it.

**Comment by pbarber** [comment]
@amoswood , thanks for the quick reply. The patch wasn't mine originally but I am currently using lynxman's fork. I'll try using your collection method and let you know how it goes.

**Comment by pbarber** [comment]
Thanks very much to @amoswood for the suggestion, the export and collect approach worked perfectly.

**Pull request closed without merging**
